
export const countries = {
    us: "🇺🇸 USA",
    ca: "🇨🇦 Canada",
    mx: "🇲🇽 Mexico",
    de: "🇩🇪 Germany",
    gb: "🇬🇧 United Kingdom",
    fr: "🇫🇷 France",
    es: "🇪🇸 Spain",
    it: "🇮🇹 Italy",
    nl: "🇳🇱 Netherlands",
    be: "🇧🇪 Belgium",
    dk: "🇩🇰 Denmark",
    se: "🇸🇪 Sweden",
    no: "🇳🇴 Norway",
    fi: "🇫🇮 Finland",
    ee: "🇪🇪 Estonia",
    lv: "🇱🇻 Latvia",
    lt: "🇱🇹 Lithuania",
    pl: "🇵🇱 Poland",
    cz: "🇨🇿 Czechia",
    sk: "🇸🇰 Slovakia",
    hu: "🇭🇺 Hungary",
    at: "🇦🇹 Austria",
    ch: "🇨🇭 Switzerland",
    pt: "🇵🇹 Portugal",
    ie: "🇮🇪 Ireland",
    is: "🇮🇸 Iceland",
    gr: "🇬🇷 Greece",
    tr: "🇹🇷 Turkey",
    ru: "🇷🇺 Russia",
    sa: "🇸🇦 Saudi Arabia",
    ae: "🇦🇪 United Arab Emirates",
    qa: "🇶🇦 Qatar",
    kw: "🇰🇼 Kuwait",
    om: "🇴🇲 Oman",
    bh: "🇧🇭 Bahrain",
    in: "🇮🇳 India",
    cn: "🇨🇳 China",
    jp: "🇯🇵 Japan",
    kr: "🇰🇷 South Korea",
    hk: "🇭🇰 Hong Kong",
    tw: "🇹🇼 Taiwan",
    sg: "🇸🇬 Singapore",
    id: "🇮🇩 Indonesia",
    th: "🇹🇭 Thailand",
    ph: "🇵🇭 Philippines",
    au: "🇦🇺 Australia",
    nz: "🇳🇿 New Zealand",
    ar: "🇦🇷 Argentina",
    br: "🇧🇷 Brazil",
    cl: "🇨🇱 Chile",
    co: "🇨🇴 Colombia",
    ec: "🇪🇨 Ecuador",
    pe: "🇵🇪 Peru",
    uy: "🇺🇾 Uruguay",
    ve: "🇻🇪 Venezuela",
    bo: "🇧🇴 Bolivia",
    py: "🇵🇾 Paraguay",
    cr: "🇨🇷 Costa Rica",
    do: "🇩🇴 Dominican Republic",
    sv: "🇸🇻 El Salvador",
    gt: "🇬🇹 Guatemala",
    hn: "🇭🇳 Honduras",
    ni: "🇳🇮 Nicaragua",
    pa: "🇵🇦 Panama",
    bs: "🇧🇸 Bahamas",
    bb: "🇧🇧 Barbados",
    cu: "🇨🇺 Cuba",
    jm: "🇯🇲 Jamaica",
    ht: "🇭🇹 Haiti",
    tt: "🇹🇹 Trinidad & Tobago",
    ag: "🇦🇬 Antigua & Barbuda",
    dm: "🇩🇲 Dominica",
    gd: "🇬🇩 Grenada",
    kn: "🇰🇳 St. Kitts & Nevis",
    lc: "🇱🇨 St. Lucia",
    vc: "🇻🇨 St. Vincent & Grenadines",
    ai: "🇦🇮 Anguilla",
    bm: "🇧🇲 Bermuda",
    ky: "🇰🇾 Cayman Islands",
    ms: "🇲🇸 Montserrat",
    tc: "🇹🇨 Turks & Caicos Islands",
    vg: "🇻🇬 British Virgin Islands",
  
    // NON EMOJIS
    cf: "Central Africa Republic",
    cm: "Camaroon",
    ly: "Libya",
    am: "Armenia",
    ao: "Angola",
    aq: "Antarctica",
    bi: "Burundi",
    bw: "Botswana",
    bz: "Belize",
    ga: "Gabon",
    ge: "Georgia",
    gh: "Ghana",
    jo: "Jordan",
    la: "Laos",
    lu:"Luxembourg",
    // add more country codes and their corresponding names as needed
  };


export const states = {
    al: "Alabama",
    ak: "Alaska",
    az: "Arizona",
    ar: "Arkansas",
    ca: "California",
    co: "Colorado",
    ct: "Connecticut",
    de: "Delaware",
    fl: "Florida",
    ga: "Georgia",
    hi: "Hawaii",
    id: "Idaho",
    il: "Illinois",
    in: "Indiana",
    ia: "Iowa",
    ks: "Kansas",
    ky: "Kentucky",
    la: "Louisiana",
    me: "Maine",
    md: "Maryland",
    ma: "Massachusetts",
    mi: "Michigan",
    mn: "Minnesota",
    ms: "Mississippi",
    mo: "Missouri",
    mt: "Montana",
    ne: "Nebraska",
    nv: "Nevada",
    nh: "New Hampshire",
    nj: "New Jersey",
    nm: "New Mexico",
    ny: "New York",
    nc: "North Carolina",
    nd: "North Dakota",
    oh: "Ohio",
    ok: "Oklahoma",
    or: "Oregon",
    pa: "Pennsylvania",
    ri: "Rhode Island",
    sc: "South Carolina",
    sd: "South Dakota",
    tn: "Tennessee",
    tx: "Texas",
    ut: "Utah",
    vt: "Vermont",
    va: "Virginia",
    wa: "Washington",
    wv: "West Virginia",
    wi: "Wisconsin",
    wy: "Wyoming",
    // add more states and their corresponding emoji flags as needed
  };