export type IVariant =
  | ""
  | "lowercase"
  | "inherit"
  | "left"
  | "card"
  | "right"
  | "dark"
  | "glow"
  | "lite"
  | "warning"
  | "center dark"
  | "account"
  | "active"
  | "pill"
  | "blue"
  | "center"
  | "disabled"
  | "select__disabled"
  | "disabled-icon"
  | "false"
  | "bump"
  | "bump pill"
  | "flat"
  | "gray"
  | "hide-sort"
  | "icon"
  | "icon-blue"
  | "invalid"
  | "link"
  | "mini"
  | "miniactive"
  | "nav-item"
  | "center nav-item"
  | "nav-item__active"
  | "null"
  | "undefined"
  | "wordmark"
  // UiCal
  | "daily"
  | "custom"
  | "monthly"
  | "dark invalid"
  | "invalid dark"
  | "dark account"
  | "account dark"
  | "primary"
  | "primary round mini"
  | "round primary"
  | "secondary"
  | "signature"
  | "signature invalid"
  | false
  // Add other combinations as needed
  ;

export type IOverlayVariant =
  | "blur"
  | "blur-disabled"
  | "disabled"
  | "dark invalid"
  | "invalid dark"
  | "dark disabled"
  | "disabled dark"
  // Add other combinations as needed
  ;
